apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-node-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "my-node-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "my-node-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000  # This is the port on which your application is running inside the pod
      nodePort: {{ .Values.service.nodePort }}  # Expose the service on the specified node port
  type: NodePort  # Ensure the service type is set to NodePort

